---
all:
  hosts:
    localhost:
      ansible_connection: local
      ansible_python_interpreter: "{{ ansible_playbook_python }}"
  children:
    laptop:
      hosts:
        csb-p1g7:
          ansible_host: bevans-thinkpadp1gen7.rmtusaz.csb
          ansible_user: bevans
