---
all:
  hosts:
    localhost:
      ansible_connection: local
      ansible_python_interpreter: "{{ ansible_playbook_python }}"
  children:
    laptop:
      hosts:
        bevans-thinkpadp1gen7.rmtusaz.csb:
          ansible_user: bevans
