---
system_config_dnf_repositories:
  - name: cursor
    description: Cursor
    baseurl: https://downloads.cursor.com/yumrepo
    gpgcheck: true
    gpgkey: https://downloads.cursor.com/keys/anysphere.asc
    enabled: true
    repo_gpgcheck: true
  - name: code
    description: Visual Studio Code
    baseurl: https://packages.microsoft.com/yumrepos/vscode
    gpgcheck: true
    gpgkey: https://packages.microsoft.com/keys/microsoft.asc
    enabled: true
    repo_gpgcheck: true
  - name: enpass
    description: Enpass password manager
    baseurl: https://yum.enpass.io/stable/$basearch/
    gpgcheck: true
    gpgkey: https://yum.enpass.io/RPM-GPG-KEY-enpass-signing-key
    enabled: true
    repo_gpgcheck: true
  - name: google-chrome
    description: Google Chrome
    baseurl: https://dl.google.com/linux/chrome/rpm/stable/$basearch
    gpgcheck: true
    gpgkey: https://dl.google.com/linux/linux_signing_key.pub
    enabled: true
    repo_gpgcheck: true
  - name: google-cloud-cli
    description: Google Cloud CLI
    baseurl: https://packages.cloud.google.com/yum/repos/cloud-sdk-el10-x86_64
    gpgcheck: true
    gpgkey: https://packages.cloud.google.com/yum/doc/rpm-package-key-v10.gpg
    enabled: true
    repo_gpgcheck: false
  - name: hashicorp
    description: Hashicorp Stable - $basearch
    baseurl: https://rpm.releases.hashicorp.com/fedora/$releasever/$basearch/stable
    gpgcheck: true
    gpgkey: https://rpm.releases.hashicorp.com/gpg
    enabled: true
    repo_gpgcheck: true
